name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image (Frontend)
        run: docker build -t myapp:latest .

      - name: Build Docker Image (Backend)
        run: docker build -t backend:latest ./backend
